# Generated by Django 4.2 on 2023-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://tse2.mm.bing.net/th?id=OIP.2-M7NuZ1n3stCKY5xY3P_gAAAA&pid=Api&P=0",
                max_length=500,
            ),
        ),
    ]
